---
- name: Configure and restart service
  hosts: all  # Specify the target hosts or host groups

  tasks:
    - name: Ensure configuration file is present
      template:
        src: /path/to/source/config.conf.j2
        dest: /etc/service/config.conf
      notify: restart service

  handlers:
    - name: restart service
      service:
        name: my_service
        state: restarted
================================================================
The playbook is named handler.yml.
It targets all hosts specified in your inventory (hosts: all).
It consists of one task and one handler:
The task ensures that a configuration file (config.conf) is present on the target hosts. 
It uses the template module to copy a Jinja2 template (config.conf.j2) to the destination path (/etc/service/config.conf).
After the task completes, it triggers the restart service handler.
The handler named restart service is notified by the task.
It uses the service module to restart a service named my_service.
Handlers are only executed when they are notified by tasks.
If no tasks notify a handler, the handler will not be executed.
Handlers are useful for triggering actions, such as service restarts, only when configuration changes require them.


        
